# -*- coding: utf-8 -*-
"""LarsonHomework1LinearRegressionlecture04_regression_house.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRLilk0DbOWGYHimnVTRJJagp8FEb1GD
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/girishkuniyal/Predict-housing-prices-in-Portland/master/ex1data2.txt"
data= pd.read_csv(url, header=None, names=['size','beds','price'])

df=data[['size', 'price', 'beds']]

Y = df['price'].values

print(Y)

Y = df['price'].values.reshape(-1,1)

print(Y)

X = data[['size','beds']].values

print(X)

from sklearn.linear_model import LinearRegression
reg = LinearRegression(fit_intercept=False).fit(X, Y)

reg.score(X, Y)

reg.coef_

reg.intercept_

reg.predict(np.array([[2980, 3]]))

from sklearn.linear_model import LinearRegression
reg1 = LinearRegression(fit_intercept=True).fit(X, Y)

reg1.score(X, Y)

reg1.coef_

reg1.intercept_

reg1.predict(np.array([[2980, 3]]))